Rename accessible
odilia-app/atspi pull request #129
Opened 2023-08-02 21:10 UTC by TTWNO

Closes #126

2023-09-06 20:38 UTC, DataTriny commented on atspi-common/src/object_reference.rs
> +pub struct ObjectReference {
Unless it was previously ruled out, I'd suggest renaming this struct `ObjectRef`. The name is quite long for a type so pervasive, and the `Ref` keyword should be known by most Rust developers.

2023-09-18 09:31 UTC, DataTriny commented
I would have also renamed `object_reference.rs` in the process. Otherwise changes look OK to me.

2023-09-18 13:55 UTC, DataTriny requested changes

2023-09-18 13:55 UTC, DataTriny commented on atspi-common/src/events/mod.rs
> +		let accessible = ObjectRef { name: body.properties.name, path: body.properties.path };
```suggestion
		let object = ObjectRef { name: body.properties.name, path: body.properties.path };
```

2023-09-18 14:25 UTC, TTWNO commented
Don't worry about the coverage failing; it just happens sometimes.

2023-09-18 14:40 UTC, luukvanderduim commented
> Don't worry about the coverage failing; it just happens sometimes.

I never worry about that. I am even unsure if that metric is even all that meaningful without knowing anything about the tests in use.
I do worry somewhat about the false sense of security a green lit '90% code-coverage' might give.

2023-09-18 14:47 UTC, DataTriny approved these changes

2023-09-18 15:27 UTC, merged