zbus 5.0
odilia-app/atspi pull request #209
Opened 2024-11-05 19:27 UTC by TTWNO

- **Update zbus dep too**
- **Upgrade atspi-common to zbus 5.x; some formatting and clippy fixes also included**
- **Update atspi-proxies to zbus 5.x**
- **Add pub modifier for public Bus,Registry,Status proxies**
- **Update atspi-connections to zbus 5.x**
- **Use new static signature assertions**
- **Fix tests so they run (many fail)**
- **Formatting**
- **Use the non-parenthesis string for comparison**
- **Fix additional tests via using string instead of static signature variation; necessary due to dynamic/static difference**
- **formatting**
- **use git instead of path**
- **Use pub modifier in traits**
- **Test signature instead of string representation**
- **use static instead of const for structure defs**
- **Use const Signature for matching**

2024-11-05 21:05 UTC, DataTriny commented
Thank you very much for the hard work @TTWNO.

I will however, once again, say that it is too soon to update to zbus 5.0 for the simple fact that it requires Rust 1.80. At the time of writing, most crates in the GUI space are not there yet.

2024-11-05 21:53 UTC, TTWNO commented
`accesskit` is still 2 versions behind latest release (and there's nothing wrong with that); do not feel pressured to start using this right away.

Would you prefer that this PR not be merged until `accesskit` is ready for it?

2024-11-05 22:11 UTC, DataTriny commented
I was not even talking about AccessKit here. Someone else did the migration to zbus 4 and I accepted it because pressure was starting to build up on us. Finalizing the update to latest atspi is on my TODO list now.

Given that the users of this crate are Odilia and most Rust UI toolkits through AccessKit, I think you should at least wait for the majority of them to bump their MSRV to 1.80.

2024-11-24 02:32 UTC, TTWNO commented
@luukvanderduim here's a little snack for you:

## `main` (baseline)

```
Benchmarking 1000 Messages into Events: Collecting 100 samples in estimated 5.8396 s (5050 iterations)
Benchmarking 1000 Messages into Events: Analyzing
1000 Messages into Events
                        time:   [1.1601 ms 1.1610 ms 1.1621 ms]
                        change: [-1.7272% -1.4957% -1.1790%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
  4 (4.00%) high mild
  5 (5.00%) high severe

     Running benches/event_parsing_100k.rs (target/release/deps/event_parsing_100k-b0fe8b8980053f77)
Gnuplot not found, using plotters backend
Benchmarking 100_000 Messages into Events
Benchmarking 100_000 Messages into Events: Warming up for 3.0000 s

Benchmarking 100_000 Messages into Events: Collecting 100 samples in estimated 11.638 s (100 iterations)
Benchmarking 100_000 Messages into Events: Analyzing
100_000 Messages into Events
                        time:   [116.47 ms 116.59 ms 116.73 ms]
                        change: [-0.6995% -0.5876% -0.4643%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 8 outliers among 100 measurements (8.00%)
  5 (5.00%) high mild
  3 (3.00%) high severe
```

## `zbus-5.0`

```
Gnuplot not found, using plotters backend
Benchmarking 1000 Messages into Events
Benchmarking 1000 Messages into Events: Warming up for 3.0000 s
Benchmarking 1000 Messages into Events: Collecting 100 samples in estimated 9.5743 s (10k iterations)
Benchmarking 1000 Messages into Events: Analyzing
1000 Messages into Events
                        time:   [944.19 µs 944.91 µs 945.56 µs]
                        change: [-18.962% -18.734% -18.564%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
  1 (1.00%) low severe
  6 (6.00%) low mild
  1 (1.00%) high mild

     Running benches/event_parsing_100k.rs (target/release/deps/event_parsing_100k-be271a74dbbe3952)
Gnuplot not found, using plotters backend
Benchmarking 100_000 Messages into Events
Benchmarking 100_000 Messages into Events: Warming up for 3.0000 s

Benchmarking 100_000 Messages into Events: Collecting 100 samples in estimated 9.3121 s (100 iterations)
Benchmarking 100_000 Messages into Events: Analyzing
100_000 Messages into Events
                        time:   [93.361 ms 93.599 ms 93.845 ms]
                        change: [-19.925% -19.719% -19.463%] (p = 0.00 < 0.05)
                        Performance has improved.

     Running unittests src/lib.rs (target/release/deps/atspi_common-0cd15493bbdcefe5)
```

One event is parsed on average every 0.94μs!

2025-01-18 19:42 UTC, TTWNO commented
Interesting; I just re-read the zbus issue that is named "downgrade to 1.80", but I guess the ultimate decision was to downgrade all the way to 1.77; interesting!

2025-02-11 19:50 UTC, DataTriny commented
I'm ready to update AccessKit to zbus 5 and so next version of atspi as well now. What's left to do here? Do you need help?

Why so many changes for a version bump? It's going to be a nightmare to review.

2025-02-11 19:53 UTC, TTWNO commented
Half of these can be squahed. I can go through them this week.

But @luukvanderduim pleasw move current work on another branch. I'll remove the latest commot from this branch when I squash the other commits.

2025-02-11 19:57 UTC, DataTriny commented
Thank you @TTWNO for your understanding. Please ask me a review when you're done.

2025-02-11 20:04 UTC, luukvanderduim commented
> Half of these can be squahed. I can go through them this week.
> 
> But @luukvanderduim pleasw move current work on another branch. I'll remove the latest commot from this branch when I squash the other commits.

Sure.
Want me to revert the last commit or will you?

2025-02-11 20:06 UTC, TTWNO commented
Either is fin3, thanks.

2025-02-16 23:22 UTC, TTWNO commented
@DataTriny 

Most of the squashable items have been squahsed. There are a lot of changed files, but most of them are small changes (adding `pub`, because `zbus` updated the way they export proxies) or updating `Signature` types since they are now completely different.

Is there anything in particular you're worried about? 

Note that this PR also bumps the version. I'll add the tag and sign the commit when we're good to go.

2025-02-18 19:50 UTC, DataTriny commented on atspi-common/src/cache.rs
> +// ((so)(so)(so)iiassusau)
I think this is not used anywhere.

2025-02-18 20:25 UTC, DataTriny commented on atspi-common/src/events/mod.rs
> +// Same as "(siiva{sv})"
We already have `EventBodyOwned::SIGNATURE` right? And the same for the Qt variant? I think removing these as part of the migration make sense because the new API to build signatures is very hard to read.

2025-02-18 20:48 UTC, DataTriny commented on atspi-common/src/object_match.rs
> +		&Signature::Array(Child::Static { child: &Signature::I32 }),
I think it would be more readable to get the signatures from Rust's `Vec` and `HashMap` implementation of the `Type` trait here.

2025-02-18 20:52 UTC, DataTriny commented on atspi-common/src/object_ref.rs
> +// Equiv to "(so)"
I'd also drop this in favor of `ObjectRef::SIGNATURE`.

2025-02-18 21:06 UTC, DataTriny requested changes
Please don't forget to update zbus crates to their latest published version. Some remarks on signatures, otherwise this looks good.

2025-02-24 20:03 UTC, TTWNO commented
Didn't mean to resolve the suggestions. Oops!

I think I got everything.

2025-02-24 20:14 UTC, DataTriny approved these changes
Looks good to me. Again, many thanks!

2025-02-24 20:14 UTC, merged

2025-02-24 21:56 UTC, TTWNO commented
Would you like a release with the upgrade ASAP? Or not in a rush?

2025-02-24 22:07 UTC, DataTriny commented
I'm currently updating AccessKit and we'd like to release new versions in the coming days. I can wait 2 days or so.

BTW using `EventBodyOwned` on the provider side is far from ideal. I now have to allocate everything just to ultimately pass a reference to `Connection::emit_signal`.

2025-02-25 03:17 UTC, TTWNO commented
> BTW using EventBodyOwned on the provider side is far from ideal. I now have to allocate everything just to ultimately pass a reference to Connection::emit_signal.

Coming soon. We have an `EventBodyBorrowed` in the making. That's why I was wondering about your timeline. What were you doing before this?

> I'm currently updating AccessKit and we'd like to release new versions in the coming days. I can wait 2 days or so.

We can do that.

2025-02-25 07:12 UTC, DataTriny commented
See here for usages of `EventBody`: https://github.com/AccessKit/accesskit/blob/7e65ac77d7e108ac5b9f3722f488a2fdf2e3b3e0/platforms/unix/src/atspi/bus.rs#L188

> Coming soon. We have an EventBodyBorrowed in the making.

Can I help get this across the finish line? Otherwise the update will have a noticeable impact on performance.

2025-02-25 10:51 UTC, luukvanderduim commented
> See here for usages of `EventBody`: https://github.com/AccessKit/accesskit/blob/7e65ac77d7e108ac5b9f3722f488a2fdf2e3b3e0/platforms/unix/src/atspi/bus.rs#L188
> 
> > Coming soon. We have an EventBodyBorrowed in the making.

Not sure if two days is enough to get the zero-copy branch in a shape I would feel comfortable with for production. 
However, what I do feel comfortable with I'll 'backport' the new `event_body` module which we have in our 'zero-copy-zb5' branch.
It currently has more parts than you strictly need, we can strip that if necessary. Most notable changes / feats:

Use unit structs `QtProperties` and `Properties` for the unused 'properties' fields
These:
-  have the respective `Type` signatures (qt: "(so)" and "a{sv}" for the common type).
- zero size when deserialized,
- serialize into minimal valid defaults
- Shrink `EventBodyOwned` / `EventBodyQT` by 1/3rd, from 144 bytes to 96 bytes.

Also adds `EventBodyBorrow` and`EventBodyQtBorrow` and conversions, defaults and tests.

> 
> Can I help get this across the finish line? Otherwise the update will have a noticeable impact on performance.

I'll let you know later today when it is in so you can tell us what you need now.

2025-02-25 11:53 UTC, luukvanderduim commented
I've pushed #223